// import url from "./apiUrl";
const api = {
  getBanners: "/slider/load_main_sliders",
  homeGames: "/game/get_main_page_games",
  adminAddClub: "/admin/add_club",
  getGame: "/game",
  adminGetScheduler: "/admin/get_weekly_schedule",
  getShowings: "/game/get_schedule",
  reserveShowing: "/game/reserve",
  adminAddGame: "/admin/add_game",
  adminAddShowing: "/admin/add_weekly_schedule",
  adminDeleteShowing: "/admin/delete_weekly_schedule",
  clubGames: "/club/games",
  clubSetBigImage: "/game/set_header_image",
  clubSetSmallImage: "/game/set_tile_image",
  gameComments: "/game/get_game_comments",
  getAdminGames: "/admin/get_games_list",
  adminUploadSmallImage: "/admin/set_tile_image",
  adminUploadBigImage: "/admin/set_header_image",
  adminGetUsersList: "/admin/get_users_list",
  adminGetClubsList: "/admin/get_clubs_list",
  adminGetCommentsList: "/admin/get_comments",
  adminCommentVerification: "/admin/update_comment_verification",
  userLogout: "/user/logout",
  adminGetTransactions: "/admin/get_transactions_list",
  search: "/game/search?",
  getAllCities: "/city/get_list",
  getAllDistricts: "/district/get_list",
  getAllGameTypes: "/game/get_type_list",
  getAllGenres: "/admin/get_genres_list",
  addComment: "/game/add_comment",
  smsRegister: "/user/sms_register",
  smsLogin: "/user/smslogin",
  adminAssetUpload: "/admin/upload_asset",
  getClub: "/club/get",
  getAllClubs: "/club/get_all",
  adminAddAdmin: "/admin/add_admin_to_club",
  adminUpdateShowing: "/admin/update_game_schedule",
  adminDeleteAsset: "/admin/delete_game_asset",
  getCaptcha: "/user/captcha",
  getUserProfileInfo: "/user/get_profile_info",
  getUserComments: "/user/get_comments",
  deleteGame: "/admin/delete_game",
  deleteClub: "/admin/delete_club",
  addDistricts: "/admin/add_district",
  addGenre: "/admin/add_genre",
  addCity: "/admin/add_city",
  sendSms: "/user/login",
  setBanner: "/admin/set_banner",
  setSlider: "/admin/add_main_slider",
  getSlider: "/admin/load_main_sliders",
  deleteSlider: "/admin/delete_slider",
};

// for (const prop in api) {
//   api[prop] = url() + api[prop];
// }
export default api;
